# Run basic tests for this app on the latest aiidalab-docker image.

name: continuous-integration

on:
  [push, pull_request]

jobs:

  pre-commit:
    # Adapted from: https://github.com/CasperWA/voila-optimade-client

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install pre-commit

    - name: Run pre-commit
      run: pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )

  test-app:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      matrix:
        tag: [ latest, stable ]
        browser: [ chrome, firefox ]
      fail-fast: false

    steps:

      - name: Check out app
        uses: actions/checkout@v2

      - name: Test app
        uses: aiidalab/aiidalab-test-app-action@v2
        with:
          image: aiidalab/aiidalab-docker-stack:${{ matrix.tag }}
          browser: ${{ matrix.browser }}
          name: quantum-espresso

      - name: Upload screenshots as artifacts
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: Screenshots-${{ matrix.tag }}-${{ matrix.browser }}
          path: 'screenshots/'

  compile-metadata:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:

      - name: Check out app
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -r metadata/requirements.txt

      - name: Compile metadata
        run: |
          python metadata/compile.py
